name: atlas-catalog

x-build-config: &build-config
  build:
    context: .
    dockerfile: Dockerfile
    platforms:
      - linux/amd64
    tags:
      - "atlas-catalog:latest"

services:

  init-db:
    <<: *build-config
    command:
      - /bin/sh
      - -c
      - "php artisan migrate --seed --force"
    container_name: init-db
    depends_on:
      - postgres
      - redis
#    environment:
#      DB_CONNECTION: pgsql
#      DB_HOST: postgres
#      DB_PORT: 5432
#      DB_DATABASE: laravel
#      DB_USERNAME: laravel
#      DB_PASSWORD: secret
    networks:
      - catalog-network

  # PHP-FPM Application Service
  app:
    <<: *build-config
    container_name: app
    depends_on:
      - init-db
    networks:
      - catalog-network
    ports:
      - "9000:9000"
    restart: unless-stopped
#    volumes:
#      - ./src:/var/www/html

  grafana:
    container_name: grafana
    depends_on:
      - postgres
    environment:
      GF_ANALYTICS_ENABLED: 'true'
      GF_ANALYTICS_CHECK_FOR_UPDATES: 'false'
      GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES: 'false'
      GF_DEFAULT_INSTANCE_NAME: grafana
      GF_EXPLORE_ENABLED: 'false'
      GF_HELP_ENABLED: 'false'
      GF_LOG_LEVEL: info
      GF_LOG_MODE: console
      GF_NEWS_NEWS_FEED_ENABLED: 'false'
      GF_PLUGINS_ENABLE_ALPHA: 'false'
      GF_PLUGINS_PLUGIN_ADMIN_ENABLED: 'false'
      GF_PLUGINS_PREINSTALL_DISABLED: 'true'
      GF_PUBLIC_DASHBOARDS_ENABLED: 'true'
      GF_SECURITY_ADMIN_PASSWORD: secret
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ALLOW_EMBEDDING: 'true'
      GF_SECURITY_DISABLE_GRAVATAR: 'true'
      GF_UNIFIED_ALERTING_ENABLED: 'false'
      GF_USERS_ALLOW_ORG_CREATE: 'false'
      GF_USERS_ALLOW_SIGN_UP: 'false'
    image: grafana/grafana:12.3.0-ubuntu
    networks:
      - catalog-network
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana

  # Nginx Web Server
  nginx:
    build:
      context: .
      dockerfile: build/nginx/Dockerfile
      tags:
        - "atlas-gateway:latest"
    container_name: nginx
    depends_on:
      - app
    networks:
      - catalog-network
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
      - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf

  # PostgreSQL Database Service
  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE:-laravel}
      POSTGRES_USER: ${DB_USERNAME:-laravel}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    image: postgres:17.6-alpine3.22
    networks:
      - catalog-network
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Redis Cache Service
  redis:
    container_name: redis
    environment: []
    image: redis:8.2.1-alpine3.22
    networks:
      - catalog-network
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data

  # RedisInsight GUI Service
  redis-insights:
    container_name: redis-insights
    depends_on:
      - redis
    environment:
      - ALLOW_ANONYMOUS_USAGE_STATS=no
      - RI_ACCEPT_TERMS_AND_CONDITIONS=true
      - RI_DATABASE_MANAGEMENT=false
      - RI_ENCRYPTION_KEY="${REDIS_ENCRYPTION_KEY:-default}"
      - RI_LOG_LEVEL=warn
      - RI_REDIS_DB=0
      - RI_REDIS_HOST=redis
      - RI_REDIS_PORT=6379
      - RI_REDIS_USERNAME=default
      - RI_REDIS_PASSWORD=
      - RI_REDIS_TLS=FALSE
    image: redislabs/redisinsight:2.70.1
    links:
      - redis
    networks:
      - catalog-network
    ports:
      - "5540:5540"
    restart: unless-stopped
    volumes:
      - redisinsight:/data

networks:
  catalog-network:
    driver: bridge

volumes:
  grafana-data:
    driver: local
  postgres-data:
    driver: local
  redis-data:
    driver: local
  redisinsight:
    driver: local
