apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
buildMetadata:
  - managedByLabel
images:
  - name: postgres
    newTag: 18.0-alpine3.22
labels:
  - pairs:
      app.kubernetes.io/name: postgres
    includeSelectors: true
    includeTemplates: true
resources:
  - resources/stateful-set.yaml
  - resources/service.yaml
  - resources/service.headless.yaml
  - resources/secret.yaml
