name: Laravel

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: '0'
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: xdebug
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          tools: composer:v2

      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
        working-directory: ./src

      - name: Prepare environment
        run: |
          cp .env.example .env
          php artisan key:generate
          touch database/database.sqlite
          chmod -R 777 storage bootstrap/cache
        working-directory: ./src

      - name: Run tests and generate reports
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
          XDEBUG_MODE: coverage
        run: |
          php artisan test --coverage-clover=coverage.xml --log-junit=junit.xml --stop-on-failure
        working-directory: ./src

      - name: Update paths
        run: |
          sed -i "s|/home/runner/work/atlas-catalog/atlas-catalog|/github/workspace|g" junit.xml
          cat junit.xml
        working-directory: ./src

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./src
          args: >
            -Dsonar.organization=angelcamposm
            -Dsonar.projectKey=angelcamposm_atlas-catalog
            -Dsonar.projectName=atlas-catalog
            -Dsonar.projectVersion=1.0.0
            -Dsonar.coverage.exclusions=bootstrap/**,config/*.php,database/**,public/index.php,routes/*.php
            -Dsonar.cpd.exclusions=config/*.php,database/**/*.php
            -Dsonar.exclusions=resources/**
            -Dsonar.log.level=WARN
            -Dsonar.php.coverage.reportPaths=coverage.xml
            -Dsonar.php.exclusions=vendor/**
            -Dsonar.php.tests.reportPath=junit.xml
            -Dsonar.scm.provider=git
            -Dsonar.sources=app
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.tests=tests
